[Configuration]
Char = "#" # Символ чата
Groups = ["admin", "semiadmin", "staff"]

[Messages]
# Плейсхолдеры:
# {username} = ник игрока
# {prefix} - префикс игрока
# {server} = название сервера
Message-Format = "<red>Ⓐ <gray>| {prefix} <gray>{username}  <red>➩ <white>{message}"